import Head from 'next/head'
import Image from 'next/image'
import TextInput from '@/components/TextInput'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import qr from 'qrcode'
import Loader from '@/components/Loader'

export default function Home({ qrcode, errorMsg, query }) {
  const [isLoading, setIsLoading] = useState(false)
  const [text, setText] = useState(query)
  const [photoURL, setPhotoURL] = useState(qrcode || '')
  const [error, setError] = useState(errorMsg || '')
  const router = useRouter()
  useEffect(() => {
    if (error.length) alert(error)
    setError('')
  }, [error])
  const getQRcode = async (e) => {
    setError('')
    setPhotoURL('')
    if (!text) {
      router.replace('/')
      return
    }
    try {
      setIsLoading(true)
      const response = await fetch(`/api/qrcode?text=${text}`)
      const data = await response.json()
      console.log(data)
      setIsLoading(false)
      if (!data.success) {
        setError(data.message)
        return
      }
      router.replace(
        {
          query: {
            text: text,
          },
        },
        undefined,
        { shallow: true }
      )
      setPhotoURL(data.data)
    } catch (error) {
      setError(error.message)
      console.log(error)
    }
  }
  return (
    <>
      <Head>
        <title>QR code generator</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`main-question-containar`}>
        <h1>QR code generator</h1>
        <p>Paste your URL here, it will generate your special QR Photo:</p>
        <TextInput setText={setText} text={text} />
        <button id='my-btn' onClick={(e) => getQRcode(e)}>
          Generate your own!
        </button>
        <div className={`coco ${photoURL.length ? '' : 'disabled'}`}>
          <div className={`co`}>
            {photoURL.length > 0 && (
              <Image alt='QRcode' src={photoURL} width={200} height={200} />
            )}
            <a href={photoURL} download='My QR code.png'>
              Download
            </a>
          </div>
        </div>
      </main>
      {isLoading && <Loader />}
    </>
  )
}

export async function getServerSideProps({ query }) {
  const { text } = query
  if (!text) return { props: {} }
  try {
    const qrCode = await qr.toDataURL(text)
    return { props: { qrcode: qrCode, query: text } }
  } catch (error) {
    return { props: { errorMsg: error.message } }
  }
}
